queries:
  - pokemon neo lot
  - pokemon neo bulk
  - pokemon neo genesis lot
  - pokemon neo discovery lot
  - pokemon neo revelation lot
  - pokemon neo destiny lot
  - pokemon wotc lot
  - pokemon wotc bulk
  - pokemon childhood collection wotc
  - pokemon base jungle fossil lot
  - pokemon team rocket lot
  - pokemon gym heroes challenge lot
  - pokemon expedition aquapolis skyridge lot
  - old pokemon cards lot
  - played pokemon vintage lot
