const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data, status, hunt, page, selectedSet = null, selectedType = "Pokémon", selectedRarity = "";
const filters = {text:'',ownership:'all',region:'all'};
async function api(path, options={}) { const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options}); const body=await res.json(); if(!res.ok) throw new Error(typeof body.detail==='string'?body.detail:'Please check your input.'); return body; }
function toast(text) { $('#toast').textContent=text; $('#toast').style.display='block'; clearTimeout(toast.timer); toast.timer=setTimeout(()=>$('#toast').style.display='none',4500); }
async function refresh() { data=await api('/api/collection'); $('#notice').textContent=data.metadata.ownership_note; }
function heading(kicker,title,subtitle) { return `<div class="page-heading"><div><h1>${title}</h1>${subtitle?`<p class="subtitle">${subtitle}</p>`:''}</div></div>`; }
function progress(label,n,total,note,klass='') { return `<article class="progress-card ${klass}"><div class="region">${label}</div><div class="number">${n} <span>/ ${total}</span></div><div class="bar"><i style="width:${n/total*100}%"></i></div><div class="progress-caption"><span>${note}</span><span>${Math.round(n/total*100)}%</span></div></article>`; }
function raritySummary(cards, title='Rarity counts') {
 const order=['Common','Uncommon','Rare','Rare Holo','Promo','Rare Shining','Unknown'];
 const groups=new Map();
 for(const c of cards){const key=c.rarity||'Unknown';if(!groups.has(key))groups.set(key,{owned:0,total:0});const g=groups.get(key);g.total++;g.owned+=c.owned?1:0;}
 const rows=[...groups].sort((a,b)=>(order.indexOf(a[0])<0?99:order.indexOf(a[0]))-(order.indexOf(b[0])<0?99:order.indexOf(b[0])));
 return `<section class="card rarity-summary"><h2>${esc(title)}</h2><p class="muted">Owned printings / catalog total.</p><div class="table-scroll"><table><thead><tr><th scope="col">Rarity</th><th scope="col">Owned / total</th><th scope="col">Missing</th></tr></thead><tbody>${rows.map(([r,g])=>`<tr><th scope="row">${esc(r==='Rare Holo'?'Holo rare':r==='Rare Shining'?'Shining rare':r)}</th><td>${g.owned} / ${g.total}</td><td>${g.total-g.owned}</td></tr>`).join('')}</tbody></table></div>${rows.length?'':'<p>No cards in this selection.</p>'}</section>`;
}
function usd(value){return value==null?'Unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value));}
function valueSummary(){const v=data.valuation;return `<section class="card rarity-summary"><h2>Estimated collection value</h2><div class="value-grid">${['raw','7','8','9','10'].map(g=>{const r=v.scenarios[g];return `<div><strong>${g==='raw'?'Ungraded':'Grade '+g}</strong><p class="value-amount">${r.priced?'≈ '+usd(r.subtotal):'Not priced'}</p><small>${r.priced} / ${r.owned} cards priced${r.priced&&r.total==null?' · partial total':''}${r.estimated?'<br>'+r.estimated+' rough estimates':''}</small></div>`;}).join('')}</div><p class="muted">Price-guide estimates for one of each owned printing. Grade totals assume every card receives that grade; Grade 10 uses the PSA 10 guide. Fees excluded.</p><details><summary>Price source and assumptions</summary><p>PriceCharting guide estimates, checked within ${v.max_age_days} days. Grade 7–8 prices marked * are rough interpolations between ungraded and Grade 9 values, not observed sales. Unchecked first edition uses standard pricing, not shadowless or other special variants. Unmatched cards are omitted, not valued at zero. Totals are estimates, not guaranteed sale prices.</p></details></section>`;}
function home() { const t=data.totals; $('#content').innerHTML=heading('','Collection','')+`<div class="progress-grid">${progress('Kanto',t.kanto,151,'Owned')}${progress('Johto',t.johto,100,'Owned')}${progress('Total',t.total,251,'Owned','total')}</div><section class="card"><div class="result"><div><h2>Exact cards</h2><p class="metric">${t.exact_cards}</p></div><a class="button" href="#cards">Manage cards</a></div><dl class="facts"><div><dt>Sets</dt><dd>${data.metadata.eligible_sets.length}</dd></div><div><dt>Missing species</dt><dd>${251-t.total}</dd></div><div><dt>Eligible species</dt><dd>${251-t.unavailable_species} / 251</dd></div></dl></section>${valueSummary()}${raritySummary(Object.values(data.cards).filter(c=>c.supertype==='Pokémon'),'Pokémon card rarities')}<section class="card" style="margin-top:16px"><h2>Find cards</h2><p>Listing contents stay hidden until you reveal them.</p><div class="actions"><a class="button" href="#hunt">Mystery hunt</a><a class="button secondary" href="#missing">Missing singles</a><a class="button secondary" href="#finds">Saved finds</a></div></section>`; }
function dex() { $('#content').innerHTML=heading('','Pokédex','Browse species and their eligible printings.')+`<div class="toolbar"><input id="dex-search" type="search" placeholder="Search name or Pokédex number" aria-label="Search Pokémon" value="${esc(filters.text)}"><select id="ownership" aria-label="Ownership"><option value="all">All species</option><option value="owned">Owned</option><option value="missing">Missing</option><option value="unavailable">No eligible printing</option></select><select id="region" aria-label="Region"><option value="all">Kanto & Johto</option><option value="1">Kanto</option><option value="2">Johto</option></select></div><p class="muted" id="dex-count"></p><div class="dex-grid" id="dex-grid" style="margin-top:18px"></div>`;
 $('#ownership').value=filters.ownership; $('#region').value=filters.region; for(const [id,key] of [['dex-search','text'],['ownership','ownership'],['region','region']]) $('#'+id).addEventListener('input',e=>{filters[key]=e.target.value; dexGrid();}); dexGrid(); }
function dexGrid() { let rows=Object.values(data.pokedex).filter(s=>(s.name.toLowerCase().includes(filters.text.toLowerCase()) || String(s.dex_number).padStart(3,'0').includes(filters.text))&&(filters.region==='all'||s.generation==filters.region)&&(filters.ownership==='all'||filters.ownership==='owned'&&s.dex_owned||filters.ownership==='missing'&&!s.dex_owned&&s.eligible_cards.length||filters.ownership==='unavailable'&&!s.eligible_cards.length)); $('#dex-count').textContent=`${rows.length} species`; $('#dex-grid').innerHTML=rows.map(s=>`<button class="dex-tile ${s.dex_owned?'owned':''} ${!s.eligible_cards.length?'unavailable':''}" data-species="${s.dex_number}"><span class="dex-no">#${String(s.dex_number).padStart(3,'0')}</span><strong>${esc(s.name)}</strong><small>${s.dex_owned?'✓ Owned':!s.eligible_cards.length?'No eligible printing':'Missing'}</small></button>`).join(''); }
function cardRow(c) { const canFirst=!['base_set_2','wizards_black_star_promos'].includes(c.set_id);const prices=data.valuation.cards[c.card_id]||{};return `<div class="row"><span class="num">#${esc(c.number)}</span><div class="grow"><strong>${esc(c.name)}</strong><small>${esc(c.set)} · ${esc(c.rarity)}${!c.dex_eligible?' · Does not fill a Dex slot':''}</small>${c.owned?`<div class="card-prices">${['raw','7','8','9','10'].map(g=>{const r=prices[g];return `<span>${g==='raw'?'Ungraded':'Grade '+g}: ${r?`<a href="${esc(r.source_url)}" target="_blank" rel="noopener noreferrer" title="${esc(r.basis)} · Checked ${esc(r.as_of)}">≈ ${usd(r.value)}${r.estimated?'*':''}</a>`:'—'}</span>`;}).join('')}</div><small>${c.first_edition?'First edition':'Standard edition estimate'} · — = unavailable · * = rough estimate</small>`:''}</div><div class="ownership"><label><input type="checkbox" data-owned="${esc(c.card_id)}" ${c.owned?'checked':''}> Owned</label><label><input type="checkbox" data-first="${esc(c.card_id)}" ${c.first_edition?'checked':''} ${!c.owned||!canFirst?'disabled':''}> First edition${canFirst?'':' (N/A)'}</label></div></div>`; }
function showSpecies(id) { const s=data.pokedex[id]; $('#detail-content').innerHTML=`<div class="eyebrow">#${String(s.dex_number).padStart(3,'0')} · ${s.generation===1?'Kanto':'Johto'}</div><h2>${esc(s.name)}</h2><p class="muted">${s.dex_owned?'Owned':'Missing'} · ${s.eligible_cards.length} eligible printings</p>${!s.eligible_cards.length?'<div class="empty">No eligible card in the selected sets. A future set expansion may add one.</div>':'<div class="eyebrow">Eligible printings</div>'+s.eligible_cards.map(k=>cardRow(data.cards[k])).join('')}`; $('#detail').dataset.species=id; if(!$('#detail').open) $('#detail').showModal(); }
function cards() { $('#content').innerHTML=heading('','My cards','Track ownership by set. Only eligible Pokémon cards count toward the Pokédex.')+`<div class="toolbar"><select id="set-select" aria-label="Select set"><option value="">All sets</option>${data.metadata.catalog_source.sets.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select><select id="type-select" aria-label="Card type"><option value="">All card types</option><option value="Pokémon">Pokémon</option><option value="Trainer">Trainer</option><option value="Energy">Energy</option></select><select id="rarity-select" aria-label="Rarity"><option value="">All rarities</option>${[...new Set(Object.values(data.cards).map(c=>c.rarity))].sort().map(r=>`<option value="${esc(r)}">${esc(r)}</option>`).join('')}</select></div><div id="rarity-summary"></div><div id="card-list"></div>`; $('#set-select').value=selectedSet||''; $('#set-select').onchange=e=>{selectedSet=e.target.value;setCards();}; $('#type-select').value=selectedType; $('#rarity-select').value=selectedRarity; $('#type-select').onchange=e=>{selectedType=e.target.value;setCards();}; $('#rarity-select').onchange=e=>{selectedRarity=e.target.value;setCards();}; setCards(); }
function setCards() {
 const scoped=Object.values(data.cards).filter(c=>(!selectedSet||c.set_id===selectedSet)&&(!selectedType||c.supertype===selectedType));
 $('#rarity-summary').innerHTML=raritySummary(scoped,`${selectedType||'All card types'} · rarity counts`);
 if(!selectedSet&&!selectedRarity){$('#card-list').innerHTML=`<div class="section-heading"><h2>Sets</h2></div><div class="set-grid">${data.metadata.catalog_source.sets.map(s=>{const cc=scoped.filter(c=>c.set_id===s.id),n=cc.filter(c=>c.owned).length;return `<button class="set-tile" data-set="${s.id}"><h3>${esc(s.name)}</h3><p>${n} / ${cc.length} ${esc(selectedType||'total')} cards owned</p><div class="bar"><i style="width:${cc.length?n/cc.length*100:0}%"></i></div></button>`;}).join('')}</div>`;return;}
 const rows=scoped.filter(c=>!selectedRarity||c.rarity===selectedRarity).sort((a,b)=>a.set_id.localeCompare(b.set_id)||Number(a.number)-Number(b.number));
 $('#card-list').innerHTML=`<p class="muted">${rows.length} printings. Changes save automatically.</p>`+(rows.length?rows.map(cardRow).join(''):'<div class="empty">No cards match these filters.</div>');
}
function huntView(single=false) { $('#content').innerHTML=heading('',single?'Missing cards':'Mystery hunt','Set a budget and search. Card identities stay hidden until you reveal them.')+`<form class="hunt-form" id="hunt-form"><label>Search pool<select id="pool"><option value="known_lots">Known lots · hidden contents</option><option value="mystery">True mystery / repacks</option><option value="singles">Missing singles</option></select></label><label>Hunt type<select id="focus"><option value="all">Anything Base → Neo</option><option value="kanto">Kanto focused</option><option value="johto">Johto focused</option><option value="rares">Missing rares</option><option value="bulk">Cheap bulk hunt</option></select></label><label class="budget">Delivered budget ($)<input id="budget" type="number" min="0" max="10000" step="0.01" value="150" required></label><label>Source<select id="source"><option value="demo">Sample finds</option><option value="live" ${status.live_configured?'':'disabled'}>Live eBay${status.live_configured?'':' · setup needed'}</option></select></label><button class="button" id="search-button">Find cards ↗</button></form><p class="result-note">${status.live_configured?'Live searches run only when you choose Live eBay and Find cards.':'Live eBay needs application credentials in your local .env. Sample finds work without them.'} Contents stay hidden. Following a revealed eBay link may expose the seller’s photos and title.</p><div id="results"></div>`; if(single)$('#pool').value='singles'; $('#hunt-form').onsubmit=async e=>{e.preventDefault(); await searchHunt(0);}; if(hunt)renderResults(); }
async function searchHunt(offset) { const button=$('#search-button');button.disabled=true;button.textContent='Searching…';try{hunt=await api('/api/hunts',{method:'POST',body:JSON.stringify({pool:$('#pool').value,focus:$('#focus').value,budget:$('#budget').value,demo:$('#source').value==='demo',offset})});renderResults();}catch(e){toast(e.message);}finally{if(button.isConnected){button.disabled=false;button.textContent='Find cards ↗';}} }
function metric(label,value) { return `<div class="metric"><span>${label}</span><b>${esc(value)}</b></div>`; }
function findCard(r,index) { return `<article class="find-card"><span class="tag ${r.demo?'badge-demo':''}">${r.demo?'Sample · ':''}${r.type==='auction'?'Auction':'Fixed price'}</span><h3>${esc(r.label)}</h3><p class="muted">${r.count??'Unknown number of'} cards · ${esc(r.confidence)}</p><div class="price">$${Number(r.delivered).toFixed(2)} <small>${r.type==='auction'?'current + shipping':'delivered'} · before tax</small></div><div class="metrics">${metric('Potential missing species',r.confidence==='Contents unknown'?'Unknown':r.dex_hits+' candidates')}${metric('Potential new printings',r.confidence==='Contents unknown'?'Unknown':r.exact_hits+' candidates')}${metric('Duplicate risk',r.duplicate_ratio==null?'Unknown':r.duplicate_ratio<.25?'Low in identified cards':r.duplicate_ratio<.6?'Medium in identified cards':'High in identified cards')}${metric('Raw value',r.raw_value==null?'Not available':'$'+r.raw_value)}${metric('Evidence score',r.score==null?'Not enough evidence':r.score+'/100 · '+Math.round(r.score_coverage*100)+'% coverage')}${r.type==='auction'?metric('Recommended max bid',r.max_bid==null?'Not enough evidence':'$'+r.max_bid):''}</div><p class="muted">${r.pool==='mystery'?'Random contents: no exact species yield claimed.':'Candidate hits are based on identified cards, not the entire lot.'}</p><button class="button secondary" data-reveal="${index}">Reveal ${r.pool==='singles'?'Pokémon':'cards'} ↗</button></article>`; }
function renderResults() { $('#results').innerHTML=`<div class="section-heading"><h2>${hunt.results.length} ${hunt.demo?'sample':'saved'} finds</h2><span class="tag ${hunt.demo?'badge-demo':''}">${hunt.demo?'Synthetic examples':'eBay snapshot'}</span></div><p class="result-note">${esc(hunt.coverage.note)} ${hunt.coverage.queries_run} / ${hunt.coverage.queries_total} search queries run.${hunt.coverage.warnings?.length?' '+esc(hunt.coverage.warnings.join(' ')):''}</p>${hunt.results.length?'<div class="hunt-results">'+hunt.results.map(findCard).join('')+'</div>':'<div class="empty">No matching results. Try a different pool or budget. Listings with unknown price or shipping are excluded.</div>'}${hunt.coverage.next_offset!=null&&$('#hunt-form')?'<button class="button secondary" id="next-batch">Search next batch ↗</button>':''}`; if($('#next-batch'))$('#next-batch').onclick=()=>searchHunt(hunt.coverage.next_offset); }
async function reveal(index) { const r=hunt.results[index];const revealed=await api(`/api/hunts/${hunt.hunt_id}/reveal/${encodeURIComponent(r.id)}`,{method:'POST'}); delete $('#detail').dataset.species; $('#detail-content').innerHTML=`<div class="eyebrow">Revealed cards${r.demo?' · Sample':''}</div><h2>${esc(revealed.title)}</h2><p class="muted">${esc(revealed.confidence)}. These are candidates, not verified ownership.</p>${revealed.cards.length?revealed.cards.map(k=>{const c=data.cards[k];return `<div class="row"><span class="num">#${esc(c.number)}</span><div><strong>${esc(c.name)}</strong><small>${esc(c.set)} · ${esc(c.rarity)}</small></div></div>`;}).join(''):'<div class="empty">Exact contents are unknown. Mystery products cannot promise specific new species.</div>'}${revealed.url?`<p class="muted" style="margin:20px 0">The seller’s page shows listing photos and names.</p><a class="button" href="${esc(revealed.url)}" target="_blank" rel="noopener noreferrer">View on eBay ↗</a>`:'<p class="muted" style="margin-top:20px">Sample listing — no purchase link.</p>'}`;$('#detail').showModal(); }
async function finds() {$('#content').innerHTML=heading('','Saved finds','Reopen a search. Card identities remain hidden until revealed.')+'<div id="history"></div><div id="results"></div>';const rows=await api('/api/hunts');$('#history').innerHTML=rows.length?rows.map(r=>`<button class="history-item" data-history="${r.id}"><span>${esc(r.pool.replaceAll('_',' '))}<small class="muted"> · ${new Date(r.created).toLocaleString()}</small></span><span class="tag ${r.demo?'badge-demo':''}">${r.demo?'Sample':'Live snapshot'} ↗</span></button>`).join(''):'<div class="empty">No saved searches yet.<br><a class="inline-link" href="#hunt">Find cards ↗</a></div>'; }
async function render() {page=location.hash.slice(1)||'home';document.querySelectorAll('[data-page]').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});try{if(page==='dex')dex();else if(page==='cards')cards();else if(page==='hunt'||page==='missing')huntView(page==='missing');else if(page==='finds')await finds();else home();}catch(e){toast(e.message);} }
let saving=false;
async function ownership(key,owned,first) {if(saving){toast('Saving—please try again in a moment');return;}saving=true;document.querySelectorAll('.ownership input').forEach(e=>e.disabled=true);try{await api('/api/cards/'+encodeURIComponent(key),{method:'PUT',body:JSON.stringify({owned,first_edition:first})});await refresh();await render();if($('#detail').open&&$('#detail').dataset.species)showSpecies($('#detail').dataset.species);toast('Collection saved');}catch(e){toast(e.message);await refresh();await render();if($('#detail').open&&$('#detail').dataset.species)showSpecies($('#detail').dataset.species);}finally{saving=false;}}
document.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el)return;try{if(el.dataset.species)showSpecies(el.dataset.species);else if(el.dataset.set){selectedSet=el.dataset.set;cards();}else if(el.dataset.reveal!=null)await reveal(Number(el.dataset.reveal));else if(el.dataset.history){hunt=await api('/api/hunts/'+el.dataset.history);renderResults();$('#results').scrollIntoView({behavior:'smooth'});}else if(el.classList.contains('close'))$('#detail').close();}catch(err){toast(err.message);} });
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.owned){const c=data.cards[t.dataset.owned];ownership(c.card_id,t.checked,t.checked&&c.first_edition);}else if(t.dataset.first){const c=data.cards[t.dataset.first];ownership(c.card_id,c.owned,t.checked);}});
window.addEventListener('hashchange',render);
try{await refresh();status=await api('/api/status');await render();}catch(e){$('#content').innerHTML='<div class="empty error">Could not load collection. '+esc(e.message)+'</div>';}
$('.skip-link').addEventListener('click', e=>{e.preventDefault();$('#content').focus();$('#content').scrollIntoView();});
